- name: Create directory
  ansible.builtin.file:
    path: /home/yanck/immich/
    state: directory
- name: Copy docker compose file to pi
  ansible.builtin.copy:
    src: ../files/
    dest: /home/yanck/immich/
    force: true
- name: Copy env file to pi
  ansible.builtin.template:
    src: ../secrets/.env.j2
    dest: /home/yanck/immich/.env
    force: true


- name: Tear down immich services
  community.docker.docker_compose_v2:
    project_src: /home/yanck/immich
    state: absent

- name: Recursively change ownership of /data
  ansible.builtin.file:
    path: "{{ gros_disque_path }}/data/{{ item }}"
    state: directory
    recurse: yes
    owner: "root"
    group: users
    mode: a=,a+rX,u+w,g+w
  loop:
    - encoded-video
    - library
    - thumbs
    - upload

- name: Create and start immich services
  community.docker.docker_compose_v2:
    project_src: /home/yanck/immich
    pull: always