---
- hosts: all
  become: yes

  vars:
    gros_disque_path: /mnt/gros_disque
    home_path_z2m: /home/yanck/z2m
    arr_user: arr_user
    arr_user_uid: 1053

  roles:
    - role: stefangweichinger.ansible_rclone
      rclone_version: 1.67.0

  tasks:
    - name: Install Packages
      include_role:
        name: install_packages
    - name: Basic Conf
      include_role:
        name: basic_conf
    - name: Setup SSL
      include_role:
        name: setup_ssl

    - name: Setup nginx
      include_role:
        name: setup_nginx

    - name: Setup mosquitto
      include_role:
        name: setup_mqtt_broker

    - name: Setup Z2M
      include_role:
        name: setup_Z2M

    - name: Setup matter server
      include_role:
        name: setup_matter

    - name: Setup home assistant
      include_role:
        name: setup_hass