---
- hosts: all
  become: yes

  tasks:
    - name: Install Packages
      include_role:
        name: install_packages
    - name: Basic Conf
      include_role:
        name: basic_conf
    - name: Setup DynDNS
      include_role:
        name: setup_dynDNS
    - name: Setup SSL
      include_role:
        name: setup_ssl

    - name: Setup nginx
      include_role:
        name: setup_nginx

    - name: Setup home assistant
      include_role:
        name: setup_hass