- name: Setup SSH option ChallengeResponseAuthentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'ChallengeResponseAuthentication'
    line: 'ChallengeResponseAuthentication no'
- name: Setup SSH option PasswordAuthentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication'
    line: 'PasswordAuthentication  no'
- name: Setup SSH option PermitRootLogin
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PermitRootLogin'
    line: 'PermitRootLogin no '
- name: Setup SSH option UsePAM
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'UsePAM'
    line: 'UsePAM  no'


- name: Add ssh rule to firewall
  community.general.ufw:
    rule: limit
    to_port: ssh
    proto: tcp
- name: Add http rule to firewall
  community.general.ufw:
    rule: allow
    to_port : http
    proto: tcp
- name: Add https rule to firewall
  community.general.ufw:
    rule: allow
    to_port : https
    proto: tcp
- name: open firewall on tcp lan
  community.general.ufw:
    from_ip: 192.168.0.0/16
    rule: allow
    proto: tcp
- name: Enable firewall
  community.general.ufw:
    state: enabled
    policy: deny

#- name: Mount USB file system
#  ansible.posix.mount:
#    src: /dev/sda1
#    path: /mnt/grosse_usb
#    fstype: ext4
#    state: mounted

- name: Mount Gros disque file system
  ansible.posix.mount:
    src: /dev/sda2
    path: /mnt/gros_disque
    fstype: ext4
    state: mounted

- name: add udev rules for RTL-SDR dongle
  ansible.builtin.copy:
    src: ../files/rtl-sdr.rules
    dest: /etc/udev/rules.d/
    force: true

- name: add password as env var for rtl-sdr
  ansible.builtin.copy:
    src: ../secrets/rtl-sdr.sh
    dest: /etc/profile.d/
    force: true

#- name: add cron for rtl-sdr
#  ansible.builtin.cron:
#    name: rtl-sdr-cron
#    minute: '*/10'
#    job: "BASH_ENV=/etc/profile /home/yanck/rtl_433_mqtt.sh 2>&1 | /usr/bin/logger -t CRONOUTPUT"