- alias: Fermeture volet buanderie
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: "60"
    - platform: state
      entity_id:
        - sensor.oneplus_de_yanek_wifi_bssid
      from: "<not connected>"
      to: "e8:9f:80:af:7d:65"
      for:
        hours: 0
        minutes: 2
        seconds: 0
  condition:
    - condition: state
      entity_id: sensor.oneplus_de_yanek_wifi_bssid
      state: "e8:9f:80:af:7d:65"
    - condition: sun
      after: sunset
      after_offset: "60"
  action:
    - delay:
        hours: 0
        minutes: 15
        seconds: 0
        milliseconds: 0
    - device_id: 306188294209698da3bebccbc34d9b0d
      domain: cover
      entity_id: d70e765e33e2e5816e9b10b6b2bd5b46
      type: close
  mode: single


- alias: Fermeture volet soleil
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: 30
  condition: [ ]
  action:
    - device_id: 7fe022109d91df709c6bb443b1321241
      domain: cover
      entity_id: db32937d3ab443d1df110aa0716d7cbc
      type: close
  mode: single

- alias: Ouverture volets soleil
  description: ""
  trigger:
    - platform: sun
      event: sunrise
      offset: 0
  condition: [ ]
  action:
    - device_id: 7fe022109d91df709c6bb443b1321241
      domain: cover
      entity_id: db32937d3ab443d1df110aa0716d7cbc
      type: open
  mode: single

- alias: PAC - target mode
  description: ""
  trigger:
    - platform: state
      entity_id:
        - input_boolean.yanek_is_home
      from: null
      to: "on"
  condition: [ ]
  action:
    - service: climate.set_preset_mode
      data:
        preset_mode: none
      target:
        entity_id: climate.general
  mode: single

- alias: PAC - Away mode
  description: ""
  trigger:
    - platform: state
      entity_id:
        - input_boolean.yanek_is_home
      from: "on"
      to: "off"
  condition: [ ]
  action:
    - service: climate.set_preset_mode
      data:
        preset_mode: away
      target:
        entity_id: climate.general
  mode: single

- alias: PAC - Éteint si trop froid dehors
  description: ""
  trigger:
    - type: temperature
      platform: device
      device_id: f61f14fbc8fe9c49348a03b527fbae54
      entity_id: 59f7c6bb9ac0de7f7c28523739993656
      domain: sensor
      below: 7
      for:
        hours: 0
        minutes: 3
        seconds: 0
  condition: [ ]
  action:
    - service: climate.turn_off
      metadata: { }
      data: { }
      target:
        entity_id: climate.general
  mode: single

- alias: PAC - Allume si + de 7
  description: ""
  trigger:
    - type: temperature
      platform: device
      device_id: f61f14fbc8fe9c49348a03b527fbae54
      entity_id: 59f7c6bb9ac0de7f7c28523739993656
      domain: sensor
      for:
        hours: 0
        minutes: 3
        seconds: 0
      above: 7
  condition: [ ]
  action:
    - service: climate.turn_on
      metadata: { }
      data: { }
      target:
        entity_id: climate.general
  mode: single


- alias: yanek_came_home
  description: ""
  trigger:
    - platform: state
      entity_id:
        - sensor.oneplus_de_yanek_wifi_bssid
      to: e8:9f:80:af:7d:65
      for:
        hours: 0
        minutes: 5
        seconds: 0
      from: null
    - platform: state
      entity_id:
        - sensor.oneplus_de_yanek_wifi_bssid
      to: e8:9f:80:af:7d:66
      for:
        hours: 0
        minutes: 5
        seconds: 0
      from: null
  condition: [ ]
  action:
    - service: input_boolean.turn_on
      metadata: { }
      data: { }
      target:
        entity_id: input_boolean.yanek_is_home
  mode: single

- alias: yanek_left_home
  description: ""
  trigger:
    - platform: state
      entity_id:
        - sensor.oneplus_de_yanek_wifi_bssid
      to: null
      from: e8:9f:80:af:7d:65
      for:
        hours: 0
        minutes: 15
        seconds: 0
    - platform: state
      entity_id:
        - sensor.oneplus_de_yanek_wifi_bssid
      to: null
      from: e8:9f:80:af:7d:66
      for:
        hours: 0
        minutes: 15
        seconds: 0
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.oneplus_de_yanek_wifi_bssid
          state: e8:9f:80:af:7d:65
        - condition: state
          entity_id: sensor.oneplus_de_yanek_wifi_bssid
          state: e8:9f:80:af:7d:66
  action:
    - service: input_boolean.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: input_boolean.yanek_is_home
  mode: single