# Loads default set of integrations. Do not remove.
default_config:

automation: !include automations.yaml
#automation sdb bas: !include automation_sdb_bas.yaml
#automation general: !include automation_general.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

device_tracker:
  - platform: luci
    host: 192.168.2.1
    username: !secret openwrt_user
    password: !secret openwrt_pwd

climate:
  - platform: generic_thermostat
    name: Général
    unique_id: generic_thermostat_general
    heater: switch.shellyplus1_pac_switch_0
    target_sensor: sensor.air_quality_monitor_ikea_temperature
    min_temp: 15
    max_temp: 25
    ac_mode: false
    target_temp: 21
    cold_tolerance: 0
    hot_tolerance: 0
    min_cycle_duration:
      minutes: 15
    away_temp: 18
    precision: 0.5

# Example configuration.yaml entry
command_line:
  - sensor:
      name: DNS resolution time
      command: "dig +retries=1 force.com | grep -A 100 'ANSWER SECTION:' | grep -Po '(?<=Query time: )[0-9a]*' || echo '-10'"
      unit_of_measurement: "mS"

schedule:
  heures_creuses:
    name: "Heures creuses"
    monday:
      - from: "02:26:00"
        to: "07:56:00"
      - from: "14:26:00"
        to: "16:56:00"
    tuesday:
      - from: "02:26:00"
        to: "07:56:00"
      - from: "14:26:00"
        to: "16:56:00"
    wednesday:
      - from: "02:26:00"
        to: "07:56:00"
      - from: "14:26:00"
        to: "16:56:00"
    thursday:
      - from: "02:26:00"
        to: "07:56:00"
      - from: "14:26:00"
        to: "16:56:00"
    friday:
      - from: "02:26:00"
        to: "07:56:00"
      - from: "14:26:00"
        to: "16:56:00"
    saturday:
      - from: "02:26:00"
        to: "07:56:00"
      - from: "14:26:00"
        to: "16:56:00"
    sunday:
      - from: "02:26:00"
        to: "07:56:00"
      - from: "14:26:00"
        to: "16:56:00"
