version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /mnt/grosse_usb/hass:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    ports:
      - "5683:5683/udp"
    networks:
      network:
        ipv4_address: 10.5.0.2

networks:
  network:
    name: proxy_network
    external: true