- name: Create directory
  ansible.builtin.file:
    path: /home/yanck/firefly/
    state: directory
- name: Copy docker compose file
  ansible.builtin.copy:
    src: ../files/
    dest: /home/yanck/firefly/
    force: true

- name: Copy env file to pi
  ansible.builtin.template:
    src: ../secrets/.env.j2
    dest: /home/yanck/firefly/.env
    force: true
- name: Copy db.env file to pi
  ansible.builtin.template:
    src: ../secrets/.db.env.j2
    dest: /home/yanck/firefly/.db.env
    force: true
- name: Tear down firefly services
  community.docker.docker_compose_v2:
    project_src: /home/yanck/firefly
    state: absent

- name: Create and start firefly services
  community.docker.docker_compose_v2:
    project_src: /home/yanck/firefly
    pull: always