- name: Create arr user
  ansible.builtin.user:
    name: "{{ arr_user }}"
    create_home: false
    group: users
    uid: "{{ arr_user_uid }}"

- name: Create directory torrents/movies
  ansible.builtin.file:
    path: "{{ gros_disque_path }}/data/torrents/movies"
    state: directory
    owner: "{{ arr_user }}"
    group: users
    mode: a=,a+rX,u+w,g+w
- name: Create directory torrents/tv
  ansible.builtin.file:
    path: "{{ gros_disque_path }}/data/torrents/tv"
    state: directory
    owner: "{{ arr_user }}"
    group: users
    mode: a=,a+rX,u+w,g+w

- name: Create directory media/movies
  ansible.builtin.file:
    path: "{{ gros_disque_path }}/data/media/movies"
    state: directory
    owner: "{{ arr_user }}"
    group: users
    mode: a=,a+rX,u+w,g+w
- name: Create directory media/tv
  ansible.builtin.file:
    path: "{{ gros_disque_path }}/data/media/tv"
    state: directory
    owner: "{{ arr_user }}"
    group: users
    mode: a=,a+rX,u+w,g+w

- name: Create directory
  ansible.builtin.file:
    path: /home/yanck/arr/
    state: directory
- name: Copy docker compose file to pi
  ansible.builtin.template:
    src: ../files/compose.yml.j2
    dest: /home/yanck/arr/compose.yml
    force: true
- name: Copy script file to pi
  ansible.builtin.copy:
    src: ../files/remove_tracker.sh
    dest: "{{ gros_disque_path }}/data/torrents/"
    force: true
    owner: "{{ arr_user }}"
    mode: u+rwx

- name: Tear down arr services
  community.docker.docker_compose_v2:
    project_src: /home/yanck/arr
    state: absent

- name: Create and start arr services
  community.docker.docker_compose_v2:
    project_src: /home/yanck/arr
    pull: always
