version: '3'
services:
  nginx:
    container_name: nginx
    image: "docker.io/amd64/nginx:1"
    restart: always
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    networks:
      network:
        ipv4_address: 10.5.0.3

networks:
  network:
    name: proxy_network
    external: true