version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      #- ./hass:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    networks:
      network:
        ipv4_address: 10.5.0.2

  nginx:
    container_name: nginx
    image: "docker.io/arm64v8/nginx:1"
    restart: always
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    networks:
      network:
        ipv4_address: 10.5.0.3

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16