- name: Create directory
  ansible.builtin.file:
    path: "{{ home_path_mosquitto }}"
    state: directory
- name: Create directory for backup
  ansible.builtin.file:
    path: /mnt/grosse_usb/mosquitto/
    state: directory
- name: Copy mosquitto conf files to pi
  ansible.builtin.copy:
    src: ../files/mosquitto/
    dest: /mnt/grosse_usb/mosquitto/config/
    mode: "600"
    owner: 1883
    force: true
- name: Copy mosquitto secrets files to pi
  ansible.builtin.copy:
    src: ../secrets/mosquitto/
    dest: /mnt/grosse_usb/mosquitto/config/
    mode: "600"
    owner: 1883
    force: true

- name: Copy docker compose file to pi
  ansible.builtin.copy:
    src: ../files/compose.yml
    dest: "{{ home_path_mosquitto }}/"
    force: true

- name: Tear down mosquitto services
  community.docker.docker_compose_v2:
    project_src: "{{ home_path_mosquitto }}"
    state: absent

- name: Create and start mosquitto services
  community.docker.docker_compose_v2:
    project_src: "{{ home_path_mosquitto }}"
    pull: always
