- name: Create directory
  ansible.builtin.file:
    path: /home/yanck/nginx/
    state: directory
- name: Copy docker compose file to pi
  ansible.builtin.copy:
    src: ../files/
    dest: /home/yanck/nginx/
    force: true

- name: Create proxy network
  docker_network:
    name: proxy_network
    driver: bridge
    ipam_config:
      - subnet: 10.5.0.0/16


- name: Tear down nginx services
  community.docker.docker_compose:
    project_src: /home/yanck/nginx
    state: absent

- name: Create and start nginx services
  community.docker.docker_compose:
    project_src: /home/yanck/nginx
    pull: true