- name: Create directory
  ansible.builtin.file:
    path: /home/yanck/hass/
    state: directory
- name: Copy docker compose file to pi
  ansible.builtin.copy:
    src: ../files/compose.yml
    dest: /home/yanck/hass/
    force: true

- name: Copy hass conf files to pi
  ansible.builtin.copy:
    src: ../files/hass/
    dest: /mnt/grosse_usb/hass/
    force: true
- name: Copy hass conf files to pi
  ansible.builtin.copy:
    src: ../files/hass_no_force/
    dest: /mnt/grosse_usb/hass/

- name: Tear down hass services
  community.docker.docker_compose:
    project_src: /home/yanck/hass
    state: absent

- name: Create and start hass services
  community.docker.docker_compose:
    project_src: /home/yanck/hass